- rspec-expectations.gemspec
This should fix the build.
See https://github.com/cucumber/aruba/commit/5b2c7b445bc80083e577b793e4411887ef295660#commitcomment-9284628 for background.
> Exclude aruba 0.6.2 for now.

- features/step_definitions/additional_cli_steps.rb
- rspec-expectations.gemspec
0.6.2 removes regexp so we need to stop using it.
> Update to aruba 0.6.2.

- lib/rspec/expectations/fail_with.rb
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/compound.rb
- lib/rspec/matchers/expecteds_for_multiple_diffs.rb
- spec/rspec/matchers/built_in/compound_spec.rb
- spec/rspec/matchers/expecteds_for_multiple_diffs_spec.rb
related to #712 
This is work in progress but some input required.
So I tried first to approach it by using special return value from `#expected` - an instance of class `ExpectedForMultipleDiffs`, but it became a mess very fast.
Then I tried to actually return more general `Expected` value and shifted responsibility of generating diffs to it.
But then it puzzled me, all the logic about composing `failure_message`-s of matchers is hidden inside of `CompoundMatcher`'s private methods, particularly in method `#failure_message`, and since diffs need to be injected inside of this `failure_message` at multiple places, I thought about actually having a special value for `failure_message` - `FailureMessage`
So the final idea is:
- have a class `LazyFailureMessage` and shift responsibility of …
> Compound matcher diff

- spec/rspec/expectations_spec.rb
- spec/rspec/matchers/built_in/all_spec.rb
- spec/rspec/matchers/built_in/be_spec.rb
- spec/rspec/matchers/built_in/compound_spec.rb
- spec/rspec/matchers/built_in/contain_exactly_spec.rb
- spec/rspec/matchers/built_in/eq_spec.rb
- spec/rspec/matchers/built_in/exist_spec.rb
- spec/rspec/matchers/built_in/has_spec.rb
- spec/rspec/matchers/built_in/have_attributes_spec.rb
- spec/rspec/matchers/built_in/include_spec.rb
- spec/rspec/matchers/built_in/output_spec.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
- spec/rspec/matchers/built_in/start_and_end_with_spec.rb
- spec/rspec/matchers_spec.rb
- spec/support/matchers.rb
- spec/support/shared_examples.rb
I wouldn't encourage users to directly define methods on `RSpec::Matchers` so we probably shouldn't, either.
> Refactor failure matcher definitions to use a recommended technique.

- spec/rspec/matchers/built_in/contain_exactly_spec.rb
This is breaking my attempts to remove our usage of `Set` in `rspec-core` because we don't require it before use here, but I also don't want to poison our own env so isolate it in a sub process (we use this trick on rspec-core to test similar things).
> Isolate a spec depending on set from the main process

- lib/rspec/expectations/fail_with.rb
- spec/rspec/expectations_spec.rb
Builds on rspec/rspec-support#181. This avoids the
cost of loading diff/lcs, pp, etc for cases where
we don’t need to print any diffs.
> Leverage new differ autoload.

- lib/rspec/matchers/built_in/be.rb
- spec/rspec/matchers/built_in/be_spec.rb
Applies the same for `be_false`. Still fails as expected, but adds an
additional message to suggest an alternative if still using the
deprecated `be_true`/`be_false`.
Little unsure of the wording here - this most likely needs revision.
https://github.com/rspec/rspec-expectations/issues/741
> Suggest `be_truthy`/`be true` when using `be_true`

- Changelog.md
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/base_matcher.rb
- lib/rspec/matchers/built_in/be.rb
- lib/rspec/matchers/built_in/contain_exactly.rb
- lib/rspec/matchers/built_in/eq.rb
- lib/rspec/matchers/built_in/include.rb
- lib/rspec/matchers/built_in/start_or_end_with.rb
- lib/rspec/matchers/dsl.rb
- lib/rspec/matchers/english_phrasing.rb
- lib/rspec/matchers/pretty.rb
- spec/rspec/matchers/built_in/have_attributes_spec.rb
- spec/rspec/matchers/english_phrasing_spec.rb
When writing a `failure_message` for a custom matcher, the methods in `Pretty` are useful.
Maybe we don't need all of them to be public, but some, like `to_sentence` would be nice.
This PR is just to get the conversation started.
> Allow custom matchers to use methods in Pretty

- lib/rspec/matchers.rb
- spec/rspec/matchers_spec.rb
Fixes https://github.com/rspec/rspec-expectations/issues/745
> Make a context where RSpec::Matchers is included respond to missing be_* or have_*

- Changelog.md
- lib/rspec/matchers/built_in/contain_exactly.rb
- spec/rspec/matchers/built_in/contain_exactly_spec.rb
Test doubles do not define `<=>` by default.
> Fix `contain_exactly` to work with test doubles.

- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
- spec/support/matchers.rb
Avoid diffing for problematic include cases.
Include#diffable? will return true unless it detects a multiline string with at least one "expected" that is included in "actual", but is not an exact match for any single line.
This was the most conservative strategy I could think of on this pass, and to my amazement it didn't cause any other tests to fail. (!)
I can squash these commits once this PR is ready, but didn't want to lose my first commit in case I needed that test again. It was by far the hardest part of the task so far!
Addresses https://github.com/rspec/rspec-expectations/issues/746
> Avoid diffing for problematic `include` cases

- spec/rspec/matchers/description_generation_spec.rb
[have(n) matchers were removed here](https://github.com/rspec/rspec-expectations/commit/8f39d4419e7b48bbc7d7a8263c0354249056b7c). This is an old, unused stub class from those tests.
Hey, at least _something_ productive came out of https://github.com/rspec/rspec-expectations/pull/769! :wink:
> Remove remnant of have(n) matcher tests

- Changelog.md
- lib/rspec/expectations/configuration.rb
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/expectations/configuration_spec.rb
- spec/rspec/matchers/built_in/base_matcher_spec.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
- spec/rspec/matchers/description_generation_spec.rb
- spec/spec_helper.rb
Issues a warning (which can be supressed) when using a bare `raise_error` call. Fixes #655.
> Warn about bare `raise_error`

- spec/rspec/matchers/built_in/be_spec.rb
This is necessary for rspec/rspec-mocks#932.
> Stop assuming the format of `test_double.inspect`.

- Changelog.md
- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
Follow up to #768.  @JonRowe said he planned to do this but I wanted to open an issue so we don't forget.
> Change error for `expect { }.not_to raise_error(something_specific)` to warn and respect new config

- benchmarks/include_matcher.rb
- features/built_in_matchers/include.feature
- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/be_between_spec.rb
- spec/rspec/matchers/built_in/include_spec.rb
Fixes #771 
Reimplements the `include` matcher to account for all divergent items (excluded when expected to be included in actual or included when expected to be excluded in actual) to be used in example failure output. Now when something is missing from an expectation of inclusion, the failure output will more helpfully tell you what exactly was missing rather than a full description of the expected items.
Most basic example:
```plaintext
Failure/Error: expect("abc").to include("a", "d", "c")
expected "abc" to include "a", "d", and "c"
Failure/Error: expect({ :a => 7, :b => 5 }).not_to include(:a => 7, :d => 3)
expected {:a => 7, :b => 5} not to include {:a => 7, :d => 3}
Failure/Error: expect("abc").to include("a", "d", "c")
expected "abc" to include "d"
Failure/Error: expect({ :a => …
```
> Show only differing results in #include

- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/base_matcher.rb
- lib/rspec/matchers/built_in/be.rb
- lib/rspec/matchers/built_in/has.rb
- lib/rspec/matchers/built_in/yield.rb
- lib/rspec/matchers/composable.rb
- lib/rspec/matchers/dsl.rb
- lib/rspec/matchers/matcher_delegator.rb
Part of #767, omits code specific to older versions of Ruby from test coverage.
> Omit all Ruby < 1.9 only code from test coverage

- features/built_in_matchers/satisfy.feature
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/satisfy.rb
- spec/rspec/matchers/built_in/satisfy_spec.rb
Closes #719
...So, awkwardly I _just_ stumbled upon https://github.com/rspec/rspec-expectations/pull/259 while searching for the issue this PR is supposed to resolve. 
@myronmarston This PR resolves the open issue as requested, but the closed issue contradicts it. Were you deciding that now this is a good idea?
TBH I had no idea you could pass a description to any matcher like that, and if that's the case I'd tend to agree with your past self :) If you still agree with that, I'll just leave it as is and instead change the documentation for `satisfy` to suggest giving a better description using the existing way.
> `satisfy` matcher custom descriptions

- .rubocop.yml
- Changelog.md
- benchmarks/caller_vs_raise_for_backtrace.rb
- cucumber.yml
- features/.nav
- features/aggregating_failures.feature
- features/step_definitions/additional_cli_steps.rb
- features/test_frameworks/minitest.feature
- lib/rspec/expectations.rb
- lib/rspec/expectations/fail_with.rb
- lib/rspec/expectations/failure_aggregator.rb
- lib/rspec/expectations/minitest_integration.rb
- lib/rspec/matchers.rb
- lib/rspec/matchers/dsl.rb
- lib/rspec/matchers/fail_matchers.rb
- spec/rspec/expectations/failure_aggregator_spec.rb
- spec/rspec/expectations/minitest_integration_spec.rb
- spec/rspec/matchers/dsl_spec.rb
This is the beginning of my solution for #733.
TODOs:
> Aggregate failures

- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
addresses: https://github.com/rspec/rspec-expectations/issues/762
I'm not totally confident this is the right strategy to go for here. @myronmarston - could there be other matchers that match on `String`/`Regexp` whose intended target would be the exception, not the message?
> RaiseError can support first arg matcher on message.

- rspec-expectations.gemspec
This PR is related to https://github.com/rspec/rspec-core/pull/1974
Thank you.
> Removed deprecated option from .gemspec

- spec/rspec/matchers/built_in/eq_spec.rb
- spec/rspec/matchers/built_in/start_and_end_with_spec.rb
- spec/spec_helper.rb
This addresses the failures from rspec/rspec-core#1971.  Not sure why they started failing and I can't repro locally but this should fix it.
> Address 1.8.7 hash ordering

- features/step_definitions/additional_cli_steps.rb
- lib/rspec/expectations/failure_aggregator.rb
Needed by an rspec-core PR that's forthcoming.
> Refactor: expose `all_exceptions` in a way that allows ordered additions.

- features/composing_matchers.feature
Noticed this typo on relishapp.
> Typo fix: contain_exactly => include

- Changelog.md
- lib/rspec/matchers/expecteds_for_multiple_diffs.rb
- spec/rspec/matchers/expecteds_for_multiple_diffs_spec.rb
It looks empty when printed, after all.
> Silence diff that is just whitespace.

- features/built_in_matchers/comparisons.feature
- lib/rspec/matchers/built_in/be.rb
- spec/rspec/matchers/built_in/be_spec.rb
Hi this is a also a follow up to #807,
I added a `begin; rescue; end` block to rescue `ArgumentError`. Should I also rescue `NoMethodError`? I thought it would be better not to rescue this one, because it is a severe user error which should not be rescued.
> Fixed bug in be_*-matcher

- Changelog.md
- lib/rspec/matchers/built_in/respond_to.rb
- spec/rspec/matchers/built_in/respond_to_spec.rb
Previously it would crash or not work properly when we were trying to
check arity of any method on target object that had overridden the
`method` method.
> Fix `respond_to` for targets that redefine `method`

- README.md
Whitespace in README from last update resulted in a failing test. This removes that whitespace
> removes whitespace from README to fix failing test

- features/built_in_matchers/README.md
What's our 1.8 deprecation policy again? Drop it in 4?
@rspec/rspec
> _Technically_, it's 1.9 _plus_

- lib/rspec/matchers/built_in/match.rb
The description for failed captures should read just like the normal 'match' description, but with the addition of the captures clause.
We shouldn't specify that either expected or actual is a string (since either could be a string).
We shouldn't use rely on to_s but rather inspec, that way the expected is printed in a consistent fashion for both the captures and non-captures cases.
> reword MatchWithCaptures description

- Changelog.md
- lib/rspec/matchers/composable.rb
- spec/rspec/matchers/composable_spec.rb
This patch fixes SystemStackError raised when diffing an Enumerable object whose `#each` includes the object itself:
```ruby
array = ['something']
array << array
expect(array).to eq([])
```
```
Failure/Error:
expect(array).to eq([])
SystemStackError:
stack level too deep
```
> Fix SystemStackError raised when diffing a recursive Enumerable object

- Changelog.md
- appveyor.yml
- lib/rspec/matchers/built_in/compound.rb
- spec/rspec/matchers/built_in/all_spec.rb
- spec/rspec/matchers/built_in/compound_spec.rb
They are harder to read when put on a single line.
Closes #747.
> Always print compound failure messages multi-line.

- lib/rspec/matchers/built_in/raise_error.rb
Made some minor refactors as stated below. 
* Removed parallel assignment in initialize. IMO makes it easier to read as well
* Break up string from one to two lines as length was very long
* Only 2 rubocop issues remain `matches?` and `warn_for_false_positives`
> Remove parallel assignment and break up string that was too long. 

- lib/rspec/matchers/built_in/contain_exactly.rb
* Shortened failure_message method by moving the failure message string out
* Moved the longer string lines into separate named methods
* Removed some duplication in the string interpolation into a separate method
* Fixed minor rubocop issue with spacing in assignment
With the changes, these lines are now <= 80 characters in length. And IMO slightly easier to read+maintain since we don't have to space pad the strings.
> Minor refactors to line lengths

- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
Fix for issue #822
https://github.com/rspec/rspec-expectations/issues/822
When the raise_error() matcher triggers a warning it does not include
the cause of the actual error. This commit changes the warning message
to include the actual error that was raised.
I've moved setting the warning message `RaiseError#warn_about_bare_error`
further down in `RaiseError##matches` because the warning message needs
an instance variable to be set in order to display the current error.
> Include current error message in raise_error warning

- benchmarks/gsub_vs_tr_single_character.rb
- lib/rspec/matchers/built_in/change.rb
* Shortened strings spanning more than 80 characters
* Replaced double quotes to single quotes inside string interpolation per rubocop
* Replaced `gsub` with `tr` in string interpolation for the performance gain of 1-1 replacements
> Minor refactors to line lengths and rubocop issues

- lib/rspec/matchers/built_in/yield.rb
* Convert non-interpolated strings to single quotes
* Simplified description method
* Swapped out + with \ for multiline strings
* Shortened some line lengths
* Remove parallel assignment
> Fix various rubocop issues and simplify yield

- lib/rspec/matchers/built_in/base_matcher.rb
Fixed some rubocop issues in this base_matcher.
* Prefer single quotes over double when there are no interpolations
* Use shorthand `&:method` instead of `|var| var.method` notation
* rubocop spacing for multi-line `if` clause
> Fix rubocop issues in base_matcher

- lib/rspec/matchers/built_in/be.rb
Minor refactoring to fix rubocop issues:
- Removed parallel assignment
- Changes double quotes to single quotes where interpolation is not needed
- Shortened some longer lines
> Fix rubocop issues in built_in matcher be.rb

- lib/rspec/matchers/built_in/raise_error.rb
Just changing 'supressed' to 'suppressed'.
> Fix typo in warnings

- lib/rspec/matchers/built_in/raise_error.rb
I'm honestly not sure how necessary this is anymore because the error message is significantly clearer in 3.x than it was in 2.x, however I reduced the max line count for the file, which it seems like the maintainers are trying to work toward based on the comments in the rubocop yaml file, so hopefully that adds some value.
> Expand warning message and reduce max line count for file to 100

- lib/rspec/expectations/handler.rb
- lib/rspec/matchers/dsl.rb
- spec/rspec/expectations/handler_spec.rb
- spec/rspec/matchers/dsl_spec.rb
Fixes #788 
This fixes two issues; The second was found after testing the first led to it, and is dependent on it.
* Fixes `match_when_negated` to work as `match` does. The definition of #match in the matcher DSL rescues ExpectationNotMetError and returns false, allowing expectations to be used in match blocks. This changes #match_when_negated to act similarly.
* Using a negative matcher _with differing values_ (ie: `expect("foo").not_to eq "bar"`) has returned `false` for a long time, instead of the handler properly raising `ExpectationNotMetError`. This changes the handler to similarly do it as the positive handler does. See commit message in 7880b129963f8196dd288bdf834167f1204fe760 for more details.
> Exception failures in `match_when_negated`; Fix `NegativeExpectationHandler::handle_matcher`

- lib/rspec/expectations/syntax.rb
- spec/rspec/expectations/extensions/kernel_spec.rb
The deprecation check uses `__method__` which is a Kernel method
that is not available on BasicObject. We can call it directly on
Kernel instead so that we avoid any `method_missing` chains that
may attempt to dispatch it to BasicObject.
> Fix deprecation check for `should` with BasicObject.

- lib/rspec/expectations/configuration.rb
- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/expectations/configuration_spec.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
Change our `warn_about_false_positives` behaviour to also allow raising on false positives, for those that like an even stricter behaviour. (we allow this with deprecations so why not!)
Closes #888
> Allow raising on false positives

- features/custom_matchers/define_block_matcher.feature
- lib/rspec/matchers/dsl.rb
- spec/rspec/matchers/dsl_spec.rb
This is an attempt at a solution for #890 , by wrapping actual "value" blocks in another closure, we should be able to captures any expectation errors internally before re-raising them, which in turn should allow us to maintain existing block behaviour but also raise nested expectations correctly from the matcher.
Thoughts? @myronmarston
> Stop block matchers from swallowing nested expectations

- Changelog.md
- features/test_frameworks/minitest.feature
- lib/rspec/expectations/expectation_target.rb
- lib/rspec/expectations/minitest_integration.rb
- spec/rspec/expectations/expectation_target_spec.rb
Minitest::Spec 5.6+ introduced an `expect` method which
was conflicting which ours. To make our integration work
we have to define `to`/`not_to`/`to_not` on `Minitest::Expectation`.
Fixes #902.
> Fix minitest integration to work on Minitest::Spec 5.6+.

- Changelog.md
- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
> Fix include matcher so that it provides a valid diff for hashes

- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
We only want to return a single hash from `expected`
if only one hash was provided.  If multiple hashes
were provided we do not want to merge them for the
purposes of diffing.
Also, we tend to favor `klass === object` checks
over `object.is_a?(klass)` since `object` could
be any user object that defines `is_a?` however
(or does not define it at all), whereas monkey
patching `===` on a core type like `Hash` would
be far less common and we simply don't support that.
@JonRowe / @yujinakayama -- can you review this since you were involved in #916?
> Fix diffing regression introduced by #916.

- features/built_in_matchers/respond_to.feature
- features/support/ruby_features.rb
- lib/rspec/matchers/built_in/respond_to.rb
- spec/rspec/matchers/built_in/respond_to_spec.rb
- Fix failure message bug when expecting 3 or more keywords.
> Add Cucumber features for new RespondTo matcher methods.

- lib/rspec/matchers/english_phrasing.rb
https://travis-ci.org/rspec/rspec-mocks/jobs/137871918
/home/travis/build/rspec/bundle/bundler/../../rspec-expectations/lib/rspec/matchers/english_phrasing.rb:28: warning: default `to_a' will be obsolete
> Attempt to work around weird 1.8.7 warning that showed up on travis:

- Gemfile
2.2.1 is broken on 1.9.2, its a dependency of Rubocop.
> Remove rubocop on 1.9.2

- Gemfile
Pin ffi on 1.8 and 1.9 on windows due to a change in required Rubies for ffi.
> Fix windows build.

- .rubocop_rspec_base.yml
- Changelog.md
- lib/rspec/matchers/dsl.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
This corrects both "a" vs "an" and "its" vs "it's" grammar errors.
> Correct grammar errors

- lib/rspec/matchers/built_in/raise_error.rb
This PR put a blank for a sense of unity as a whole warning message.
> Change the `warn_about_negative_false_positive` message

- lib/rspec/matchers/built_in/yield.rb
- spec/rspec/matchers/built_in/yield_spec.rb
This change makes `yield_with_args(matcher)` evaluate the matcher as soon as the arguments are yielded, rather than after the block has run.
I'll demonstrate the problem this solves with an example using Rails's `ActiveRecord::Relation.create`. This method takes a block. It constructs a record object, yields it, saves the record in the database, then returns it.
I'd like to be able to write a test like this:
```ruby
it "yields the record before saving" do
expect { |b| Dog.create(&b) }.to yield_with_args(be_new_record)
end
it "returns the saved record" do
expect(Dog.create).not_to be_new_record
end
```
Currently, this doesn't work. The `be_new_record` matcher is only evaluated _after_ the block is finished executing, which means that the record has already been saved and so no longer …
> yield_with_args: match immediately

- features/implicit_docstrings.feature
It was contradicted by the expected output for the feature.
> Fix incorrect comment in docs.

- Changelog.md
- features/built_in_matchers/change.feature
- features/built_in_matchers/satisfy.feature
- features/define_negated_matcher.feature
- features/support/ruby_features.rb
- features/test_frameworks/minitest.feature
- lib/rspec/expectations.rb
- lib/rspec/expectations/block_snippet_extractor.rb
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/change.rb
- lib/rspec/matchers/built_in/satisfy.rb
- spec/rspec/expectations/block_snippet_extractor_spec.rb
- spec/rspec/matchers/built_in/change_spec.rb
- spec/rspec/matchers/built_in/satisfy_spec.rb
This closes #937.
This PR depends on https://github.com/rspec/rspec-core/pull/2420 and https://github.com/rspec/rspec-support/pull/315.
> Improve failure message of #change matcher with block and #satisfy matcher by including the block snippet

- lib/rspec/matchers/built_in/base_matcher.rb
- lib/rspec/matchers/built_in/change.rb
- lib/rspec/matchers/built_in/satisfy.rb
- lib/rspec/matchers/dsl.rb
- spec/rspec/matchers/built_in/change_spec.rb
- spec/rspec/matchers/built_in/satisfy_spec.rb
Follow-up to https://github.com/rspec/rspec-expectations/pull/987.
The interface is not smart but we cannot pass matcher name to the constructor with the current matcher protocol.
> Support block snippet extraction with aliased matchers

- lib/rspec/expectations/block_snippet_extractor.rb
- spec/rspec/expectations/block_snippet_extractor_spec.rb
Ref: https://github.com/rspec/rspec-expectations/issues/989
> Fix NoMethodError raised with &:symbol proc in #change and #satisfy

- features/syntax_configuration.feature
Many times I have looked at, or copy-pasted, the stanza from https://relishapp.com/rspec/rspec-expectations/v/3-6/docs/syntax-configuration which goes:
```ruby
RSpec.configure do |config|
config.expect_with :rspec do |c|
c.syntax = :expect
end
end
```
This is unsatisfying, because of the two nested blocks perhaps, but even more so because of the variable `c`. Does it stand for "configuration"? If so, how is it different from `config`? I didn't really think of fixing this until I saw https://relishapp.com/rspec/rspec-mocks/v/3-6/docs/old-syntax which names the analogous variables `mocks` instead of `c`. And so epiphany struck: not only is `expectations` a better name than `c` (just in general), but it also helps with another confusion: the need to set expect syntax both for `expect_with` …
> Use clearer variable names in documentation (features).

- lib/rspec/matchers.rb
Fixes #1013.
/cc @yujinakayama
> Ensure alias matchers are included in our docs.

- spec/rspec/matchers/built_in/have_attributes_spec.rb
Hi! This PR fixes 3 failing tests due to the order of diffs printing out changed by:
https://github.com/rspec/rspec-support/pull/334
> Test fix for hash ordering for PR: rspec-support/pull/334

- lib/rspec/matchers/built_in/change.rb
- spec/rspec/matchers/built_in/change_spec.rb
This patch makes failure messages better if user uses compound matcher.
example
```ruby
expect { do_something }.to \
change(ModelA, :count).from(0).to(1)
.and(change(ModelB, :count).from(0).to(1))
.and(change(ModelC, :count).from(0).to(1))
```
```
expected #count to have initially been 0, but was 2
...and:
expected #count to have initially been 0, but was 1
```
This message is not user friendly because user cannot detect failed matchers.
```
expected `ModelB.count` to have initially been 0, but was 2
...and:
expected `ModelC.count` to have initially been 0, but was 1
```
In this case, user can detect failed matchers easily
> Add receiver info to ChangeDetails#value_representation

- Changelog.md
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/change.rb
- spec/rspec/matchers/built_in/change_spec.rb
> Use `hash` for `change` matcher to handle deeply nested objects.

- Gemfile
- lib/rspec/expectations/minitest_integration.rb
- lib/rspec/expectations/syntax.rb
- lib/rspec/matchers/built_in/contain_exactly.rb
- lib/rspec/matchers/composable.rb
- lib/rspec/matchers/generated_descriptions.rb
* Added @private tag for nested class (no longer inherits).
* Included full method definition in generated should/should_not docs.
* Used const_set for constant redefinition, since using = confuses YARD.
* Added short descriptions to methods that are @api private. Could
probably just @private the lot but didn't want to make that decision
here.
> Update yard to 0.9.12, motivated by CVE.

- .rubocop.yml
- .rubocop_rspec_base.yml
- Gemfile
- lib/rspec/expectations/block_snippet_extractor.rb
- lib/rspec/matchers/built_in/compound.rb
- lib/rspec/matchers/built_in/contain_exactly.rb
- lib/rspec/matchers/built_in/has.rb
- lib/rspec/matchers/built_in/respond_to.rb
- lib/rspec/matchers/built_in/satisfy.rb
- lib/rspec/matchers/english_phrasing.rb
- lib/rspec/matchers/generated_descriptions.rb
- script/functions.sh
Defaulted most new things to off, though tried to keep performance and linters.
Note that `.rubocop_rspec_base` doesn't 100% match up with `rspec-dev` because I was adding to it as we went along. Once these are all merged I'm planning to ensure they're all consistent.
> Upgrade rubocop, motivated by CVE.

- DEV-README.md
- README.md
See https://github.com/rspec/rspec-core/pull/2518.
> Use https:// instead of git:// URLs in READMEs

- Gemfile
FFI changed their minimum supported ruby version, so we'll have to pin it.
See https://travis-ci.org/rspec/rspec-expectations/jobs/354893396
> Pin ffi on RBX / 1.8

- lib/rspec/expectations/configuration.rb
- spec/rspec/expectations/configuration_spec.rb
Tests were leaking config changes.
It should fix #951
> Fix tests for 951 + rdoc first word needs to match the variable

- lib/rspec/expectations/configuration.rb
See : https://github.com/rspec/rspec-expectations/pull/1056#discussion_r184113835
> Add doc to inform that max_formatted_output_length can be set to nil

- Should.md
This change updates `Should.md` to include a description about `is_expected` as suggested in #994.
> Update Should.md to suggest is_expected in one-liners

- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
This PR should fix #1068.
With the change in #1012, `RSpec::Matchers::BuiltIn::Include` calls `#to_hash` to actual value. If actual value is a`ActiveSupport::HashWithIndifferentAccess`, `#to_hash` converts to ["a hash with string keys"](https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html#method-i-to_hash). This behavior causes expectations like `expect(hsh).to include(:foo)` fail as reported in #1068.
This PR change to call `#to_hash` only when object is not a hash. Because `ActiveSupport::HashWithIndifferentAccess` inherits `Hash`, it will not call `#to_hash`, and `expect(hsh).to include(:foo)` should pass.
> Call #to_hash only when object is not a Hash in RSpec::Matcher::BuiltIn::Include

- lib/rspec/matchers/built_in/respond_to.rb
- spec/rspec/matchers/built_in/respond_to_spec.rb
Following on from #1071 when we're checking the arity of a method for `respond_to` and the method being checked is a standard library `new` method, then we should actually check the method signature for the instance method `initialize`. This is similar to what we do in `rspec-mocks` for verifying doubles.
/cc @myronmarston as you wrote the inspiration!
> Support checking `initialize` when checking `respond_to(:new)`

- lib/rspec/matchers/built_in/compound.rb
- spec/rspec/matchers/composable_spec.rb
When an unexpected local jump (and probably some other conditions) happens in some composed matchers, this result in an unexpected KeyError.
Fixes #1074
> Handle unexpected Index / KeyError when looking up match results

- features/custom_matchers/define_block_matcher.feature
- features/custom_matchers/define_matcher.feature
- features/custom_matchers/define_matcher_with_fluent_interface.feature
- features/implicit_docstrings.feature
- lib/rspec/expectations/handler.rb
- spec/rspec/matchers/description_generation_spec.rb
> [In version 2.11 `expect` method was introduced which is now the recommended way to define expectations on an object.](https://github.com/rspec/rspec-expectations/blob/955d603421fa50e739662983f8dc09b88ccaf731/Should.md#should-and-should_not-syntax) 
When `expect` is used without a description, "should" is used in the description that is generated.
- 473dc26 describes the change that we would like to see in the world
- bfbc2b9 is my naive attempt to fix this
> Replace "should" with "is expected to" in Generated Descriptions

- features/built_in_matchers/raise_error.feature
Being new to rspec, it wasn't clear that I could pass composed matchers to 'raise_error'.  This commit adds an example of a chained matcher being passed to 'raise_error'. This is useful for testing custom attributes on an error while still satisfying the one 'expect' statement per test case enforced by rubocop-rspec. 
See https://github.com/rubocop-hq/rubocop-rspec/issues/379 for more details.
> Add chained matchers example to raise_error

- lib/rspec/matchers/built_in/change.rb
- spec/rspec/matchers/built_in/change_spec.rb
#1034 introduced a hash comparison in addition to equality comparison, and it broke the following examples (using `rspec-rails`):
it { expect { 'noop' }.not_to change { country.reload.cities } }
a workaround to that was to use the `.to_a` on the relation:
it { expect { 'noop' }.not_to change { country.reload.cities.to_a } }
and the underlying problem is with the objects that are changing their hash during the comparison.
[Notable example](https://github.com/rails/rails/blob/788eb51df3007d94b266965433b0be88a23b84c5/activerecord/lib/active_record/associations/collection_proxy.rb#L959):
def ==(other)
load_target == other
end
The problem is originally described [here](https://github.com/rspec/rspec-expectations/issues/1030#issuecomment-450823945), and the proposed solution was to raise the …
> Handle sudden subject hash change

- Gemfile
https://github.com/ffi/ffi/pull/683
Related:
- https://github.com/ffi/ffi/issues/699
> Deal with new ffi Ruby version requirement

- Gemfile
- features/step_definitions/additional_cli_steps.rb
- features/support/disallow_certain_apis.rb
- features/support/env.rb
- rspec-expectations.gemspec
- Bump dependency version
- Fix deprecations
- Limit version of transitive dependency on contracts gem on old Rubies
> Update Aruba to version 0.14.10

- lib/rspec/matchers.rb
The `@!method` tag for `RSpec::Matchers#expect` references `ExpectationTarget`, but that class is not exposed there. `Expectations::ExpectationTarget` resolves correctly.
> Add Expectations namespace to ExpectationTarget tags.

- Changelog.md
- lib/rspec/matchers/dsl.rb
- spec/rspec/matchers/dsl_spec.rb
> Add support for not swallowing expectation errors when matching negated blocks

- benchmarks/hashing_large_objects.rb
- lib/rspec/matchers/built_in/change.rb
- spec/rspec/matchers/built_in/change_spec.rb
If an object is `==` and it's `hash` results are `==` it can still have changed, as it seems instance variable contents are not considered changes. One solution to this problem is to also compare the hashes of the instance attributes. This might have some performance problems so I'm not totally convinced this is the go but it does solve the problem.
> Improve `change` mather detection of objects that have changed.

- lib/rspec/matchers/expecteds_for_multiple_diffs.rb
- spec/rspec/matchers/expecteds_for_multiple_diffs_spec.rb
In few cases the object tested implement `inspect` but the eq matcher
will see a difference when doing ==.
This can lead to a misleading output like this one:
```
Failures:
1) Foo confuses users with an empty diff
Failure/Error: Foo.something(Foo.new)
#<Foo (class)> received :something with unexpected arguments
expected: ("foobar")
got: ("foobar")
Diff:
```
This change add a notice to help to understand this failed expectation.
Fix: https://github.com/rspec/rspec-support/issues/274
> Notice when object implement inspect but == is different

- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
Usage of `nil` with `raise_error` is with a high chance unintentional, including negation.
Fixes #1142
> Emit a special warning when `nil` is passed to `raise_error`

- Changelog.md
- features/built_in_matchers/include.feature
- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
To match
```ruby
hash = {OpenStruct.new(value: :special) => true}
```
a workaround had to be used
```ruby
expect(hash.to_a)
.to contain_exactly([have_attributes(value: :special), true])
```
This change makes it simpler:
```ruby
expect(hash)
.to include(have_attributes(value: :special) => true)
```
Found here: https://github.com/rubocop-hq/rubocop-rspec/pull/851#discussion_r362733064
> Improve composability of `include` matcher

- Changelog.md
- lib/rspec/matchers/built_in/have_attributes.rb
- lib/rspec/matchers/built_in/respond_to.rb
- spec/rspec/matchers/built_in/have_attributes_spec.rb
- spec/rspec/matchers/built_in/respond_to_spec.rb
Some objects using dynamic attributes (Rails) don't always define methods, but we require them to when checking the number of arguments a method `responds_to`, convert the error into something explicit that explains this. 
As a follow up this then means that the `have_attributes` matcher will never work with such objects as it always checks that an attribute method has `0` arguments. So we add a private api to allow the `have_attributes` matcher to check arguments when they are defined normally, but suppress the warning generated and consider that a pass.
Fixes #1162
> Handle broken method handles in `respond_to` and `have_attributes` matchers.

- Changelog.md
- features/aggregating_failures.feature
- lib/rspec/expectations/failure_aggregator.rb
- spec/rspec/expectations/failure_aggregator_spec.rb
https://github.com/rspec/rspec-expectations/issues/1160
changed from this return
```
Got 3 failures from failure aggregation block:
1) expected 1.eql?(2) to return true, got false
2) expected 2.eql?(3) to return true, got false
3) expected 3.eql?(4) to return true, got false (RSpec::Expectations::MultipleExpectationsNotMetError)
./features/steps_definitions/test_aggregate_failures_steps.rb:16:in 'some scenario description'
features/gherkins/test_aggregate_failures.feature:5:in '* some scenario description'
```
to it
```
Got 3 failures from failure aggregation block:
1) expected 1.eql?(2) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:28
2) expected 2.eql?(3) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:29 …
```
> Fix #1160 - aggregate_failures without line path

- lib/rspec/matchers/built_in/yield.rb
- spec/rspec/matchers/built_in/yield_spec.rb
This fixes two misuses of `yield_control`.
The following resulted in strange failures
```
expect{ .. }.to yield_control.at_least(:trice)
```
Worse, the following doesn't test what is thought to be tested:
```
expect{ .. }.to yield_control.at_least(2).at_most(4).times
```
This PR fixes both.
> yield_control hardening

- Changelog.md
- lib/rspec/matchers/built_in/yield.rb
- spec/rspec/matchers/built_in/yield_spec.rb
> Add support for multiple yield control combinations

- lib/rspec/matchers/dsl.rb
- spec/rspec/matchers/dsl_spec.rb
> Fix Ruby 2.7 keyword args deprecation in DSL

- lib/rspec/matchers/built_in/be_within.rb
- spec/rspec/matchers/built_in/be_within_spec.rb
The way `@delta * @expected.abs` is ordered currently, the expected
object *must* coerce into a Numeric to work with `#percent_of`.
Example of where this falls down:
```
expect(Weight.new("5 lb"))
.to be_within(20).percent_of(Weight.new("4 lb"))
```
This is a statement that makes logical sense, but impossible to do with
`@delta * @expected.abs`.
By swapping the order, the expected merely has to respond to `#abs` and
`#*` and also be comparable.
I was debating making a test, but I couldn't think of a class in the stdlib that would trigger this problem and didn't want to write a whole large class just to swap the order of two variables.
> swap ordering for values with units

- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/be.rb
- lib/rspec/matchers/built_in/has.rb
- spec/rspec/matchers/built_in/be_spec.rb
- spec/rspec/matchers/built_in/has_spec.rb
Alternative to #1184 that doesn't use rspec-support meta magic.
> Ensure that has_<n> matcher works silently with keyword arguments

- lib/rspec/matchers/english_phrasing.rb
- spec/rspec/matchers/english_phrasing_spec.rb
We're currently treating all Enumerables as an Array in this method,
resulting in a Hash being formatted as a list of two-element key-value
arrays.
This results in unexpected formatting in the default failure message for
a custom matcher when the `expected` value is a Hash.
This commit updates `EnglishPhrasing.list` to no longer format a Hash as
if it were an Array.
Fixes #1192.
Before:
```
Failure/Error: expect(nil).to custom_match({a: 1, foo: 'bar', bang: Object.new})
expected nil to custom match [:a, 1], [:foo, "bar"], and [:bang, #<Object:0x00007fb89542bad0>]
```
After:
```
Failure/Error: expect(nil).to custom_match({a: 1, foo: 'bar', bang: Object.new})
expected nil to custom match {:a=>1, :bang=>#<Object:0x00007f9f363b0b28>, :foo=>"bar"}
```
> Improve Hash formatting in `EnglishPhrasing.list`

- .travis.yml
- Gemfile
- features/custom_matchers/define_diffable_matcher.feature
- features/diffing.feature
- features/support/diff_lcs_versions.rb
- spec/rspec/expectations/fail_with_spec.rb
- spec/rspec/matchers/built_in/have_attributes_spec.rb
- spec/rspec/matchers/built_in/include_spec.rb
- spec/rspec/matchers/built_in/match_spec.rb
- spec/rspec/matchers/dsl_spec.rb
Builds on rspec/rspec-support#421 to add support for both diff-lcs versions in rspec-expectations spec suite.
Once again this is pretty much just header changes.
> Fix differ support

- Gemfile
This is an attempt to fix the rspec-mocks build, its the only difference in the Gemfile I can see and its mentioned in the output.
> Remove rubysl

- lib/rspec/matchers/built_in/be.rb
- spec/rspec/matchers/built_in/be_spec.rb
We rescue `ArgumentError` and `NoMethodError` when checking comparison operators for objects, this is due to our desired behaviour to fail this matcher and not blow up when encountering things like `'a' < 1` or internal comparisons of attributes. However when negated these errors cause the matcher to pass, which is obviously not the intent of the rescue, so we now do that separately.
It's debatable if we should stop this behaviour in a future version if the objects being compared are more complicated methods but for now this helps.
Fixes #1207
> Prevent be operator false positives

- Changelog.md
- features/built_in_matchers/include.feature
- lib/rspec/matchers/built_in/count_expectation.rb
- lib/rspec/matchers/built_in/include.rb
- lib/rspec/matchers/built_in/yield.rb
- spec/rspec/matchers/built_in/include_spec.rb
This allows to specify how many times an element should be included:
```
expect([1, 2, 1]).to include(1).at_most(3).times
expect('hello').to include(/l/).twice
```
Note: Not implemented for `include(1, 2, 3)` nor for hash cases.
Also: This PR build on #1167.
> Allow count constraint on `include` matcher

- features/built_in_matchers/predicates.feature
- lib/rspec/matchers/built_in/has.rb
- spec/rspec/matchers/built_in/has_spec.rb
- spec/rspec/matchers/description_generation_spec.rb
This PR improves `Has`'s output and makes it consistent with `BePredicate`:
1) Fixes the failure message where the result was not true or false. It used to say ", got true/false" no matter what the results are. So it could say "expected ... to return false, got true" when in actuality it's expecting the result to be falsey (upcoming PR) and it got a result of `42`!
2) Failure message for now outputs the receiver.
3) The description:
> ...is expected to have taste for "wine", "cheese"
becomes:
> is expected to have taste for "wine" and "cheese"
Misc: I also changed a feature example because it was showing a custom matcher `has_all_string_keys` which, while instructive, could be misinterpreted as an actually useful matcher when the builtin matchers are much better here (e.g. `all(be_a …
> Factorize PredicateMatcher. Improve failure message for `Has`.

- Changelog.md
- features/built_in_matchers/predicates.feature
- features/test_frameworks/minitest.feature
- lib/rspec/expectations/configuration.rb
- lib/rspec/matchers/built_in/has.rb
- spec/rspec/matchers/built_in/be_spec.rb
- spec/rspec/matchers/built_in/has_spec.rb
- spec/spec_helper.rb
This PR adds a config setting `strict_predicate_matchers` which makes the checks for the dynamic predicate matchers strict. Default is `false` but for internal specs the setting is changed to `true` in `spec_helper`.
It changes the failure messages in the non-strict case from "expected ... to return true/false, ..." to  "expected ... to be truthy/falsey, ...".
It builds on #1195
> Strict predicate

- Changelog.md
- lib/rspec/expectations/failure_aggregator.rb
- spec/rspec/expectations/failure_aggregator_spec.rb
Allows the result of `aggregate_failures` to be asserted on if desired, fixes #1223
> Return true from aggregate_failures

- spec/rspec/matchers/legacy_spec.rb
https://github.com/rspec/rspec-support/pull/452/checks?check_run_id=1566708254
```
-["include {:message => (match /legacy\\s+RSpec\\s+matcher/), :call_site => (include \"/home/runner/work/rspec-support/rspec-expectations/spec/rspec/matchers/legacy_spec.rb:31\")}"]
+[{:message=>
+   "#<#<Class:0x000055fcd6e44840>:0x000055fcd6e52bc0> implements a legacy RSpec matcher\nprotocol. For the current protocol you should expose the failure messages\nvia the `failure_message` and `failure_message_when_negated` methods.\n(Used from /home/runner/work/rspec-support/rspec-expectations/spec/rspec/matchers/legacy_spec.rb:31:in `block (4 levels) in <module:Matchers>')\n",
+  :type=>"legacy_matcher"}]
```
See https://github.com/rspec/rspec-support/pull/452
> Fix ill-defined warn expectation

- spec/spec_helper.rb
See: https://github.com/rspec/rspec-core/issues/2832
> Refactor spec setup to use :apply_to_host_groups

- Changelog.md
- features/built_in_matchers/predicates.feature
- features/test_frameworks/minitest.feature
- lib/rspec/expectations/configuration.rb
- spec/rspec/expectations/configuration_spec.rb
- spec/rspec/matchers/built_in/has_spec.rb
- spec/spec_helper.rb
Depends on:
- https://github.com/rspec/rspec-mocks/pull/1397
- https://github.com/rspec/rspec-support/pull/486
> Turn strict_predicate_matchers on by default

- Changelog.md
- features/custom_matchers/define_matcher_with_fluent_interface.feature
- lib/rspec/expectations/configuration.rb
- lib/rspec/matchers/dsl.rb
- spec/rspec/expectations/configuration_spec.rb
- spec/rspec/matchers/dsl_spec.rb
- spec/spec_helper.rb
As discussed in https://github.com/rspec/rspec/issues/61#issuecomment-754968435
Depends on:
- https://github.com/rspec/rspec-core/pull/2848
- https://github.com/rspec/rspec-rails/pull/2444
> Remove `include_chain_clauses_in_custom_matcher_descriptions` option

- Changelog.md
- lib/rspec/matchers/built_in/has.rb
- spec/rspec/matchers/built_in/be_spec.rb
> Remove support for present tense predicates

- Changelog.md
- lib/rspec/expectations/expectation_target.rb
- lib/rspec/matchers/built_in/change.rb
- lib/rspec/matchers/built_in/output.rb
- lib/rspec/matchers/built_in/raise_error.rb
- lib/rspec/matchers/built_in/throw_symbol.rb
- lib/rspec/matchers/built_in/yield.rb
- spec/rspec/matchers/built_in/change_spec.rb
- spec/rspec/matchers/built_in/yield_spec.rb
- spec/support/shared_examples/block_matcher.rb
https://blog.rubystyle.guide/rspec/2019/07/17/rspec-implicit-block-syntax.html 
https://rspec.rubystyle.guide/#implicit-block-expectations
Spec changes are due to:
```ruby
matcher.matches?(invalid_value)
```
doesn't work with block-only matchers, as no block is passed in, and it fails with a message:
1) RSpec::Matchers::BuiltIn::Change behaves like an RSpec block-only
matcher uses the `ObjectFormatter` for `failure_message`
Failure/Error: expect(message).to include("detailed inspect")
expected "expected `@k` to have changed, but was not given a block"
to include "detailed inspect"
The redundant (due to existing check in ExpectationTarget) `Proc === @event_proc` checks were removed, as an error is raised earlier than those checks.
Also see:
- …
> Restrict block matchers use with value expectations

- lib/rspec/matchers/built_in/change.rb
- spec/support/shared_examples/block_matcher.rb
I've overlooked to remove this in #1285 after resolving conflicts with #1139
> Remove leftovers from #1285

- lib/rspec/expectations/expectation_target.rb
Both does not raise error in `bundle exec yard`, but looks wrong syntax in https://yardoc.org/types.html.
Or https://github.com/lsegal/yard-types-parser is wrong? Looks an ancient project 😓
> Fix YARD type syntax

- lib/rspec/expectations/expectation_target.rb
See https://github.com/rspec/rspec-collection_matchers/pull/48
If a matcher supports dynamic arbitrary methods called on it, e.g.  `have_at_least(100).bucks`, it would also consider a `supports_value_expectations?` call as a dynamic part.
Instead of calling `supports_*?` methods on a matcher, explicitly check if it responds to it.
Symmetrical change for `main` that suffers when `rspec-rails` `4.1.0.pre` is used and `rspec-expectations` `3.11.0.pre` is at https://github.com/rspec/rspec-expectations/pull/1294
> Fix support for dynamic matchers

- lib/rspec/matchers/built_in/change.rb
- lib/rspec/matchers/built_in/output.rb
- lib/rspec/matchers/built_in/raise_error.rb
- lib/rspec/matchers/built_in/throw_symbol.rb
BlockExpectationTarget enforces the target to be a block already.
> Remove redundant checks for block expectations

- features/built_in_matchers/include.feature
- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
`#expected` has a [special case](https://github.com/rspec/rspec-expectations/commit/8693ecb75) for single `Hash` and returning this
single `Hash` instead of `[Hash]`, so `expected.first` returns first
`key => value` pair and matcher suddenly fails
> Fix `expect(Array).to include(Hash).times` case

- Gemfile
- cucumber.yml
- features/support/diff_lcs_versions.rb
- features/support/disallow_certain_apis.rb
- features/support/ruby_features.rb
- rspec-expectations.gemspec
- spec/rspec/matchers/built_in/contain_exactly_spec.rb
This PR allows more recent Rubies to use more recent versions of Cucumber, while still supporting older Cucumber versions.
> Update Cucumber so that in runs across a range of Rubies

- lib/rspec/matchers.rb
- spec/rspec/matchers/aliases_spec.rb
This improves readability when used as an argument matcher.
```
expect(obj).to receive(:msg).with(an_array_matching([1, 2]))
```
> Add an_array_matching alias for match_array

- spec/rspec/expectations/failure_aggregator_spec.rb
Adding the correct `exception_complement` implementation for TruffleRuby allows all of the `rspec-expectations` specs to pass.
> Add exception_complement for TruffleRuby

- spec/rspec/expectations_spec.rb
This PR is organized similar to `core_spec.rb`:
https://github.com/rspec/rspec-core/blob/1a1788768ec39a1f252ea756ed9b53cdd21124d5/spec/rspec/core_spec.rb#L17
Fixes this failure on TruffleRuby:
```
1) RSpec::Expectations behaves like library wide checks only loads a known set of stdlibs so gem authors are forced to load libs they use to have passing specs
Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
expected: []
got: ["/Users/bfish/Documents/truffleruby-ws/graal/sdk/mxbuild/darwin-amd64/GRAALVM_67F33FC705_JAVA11/graa...VA11/graalvm-67f33fc705-java11-22.2.0-dev/Contents/Home/languages/ruby/lib/truffle/truffle/cext.rb"]
(compared using ==)
```
> Add allowed feature path for TruffleRuby library wide checks

- lib/rspec/matchers/built_in/contain_exactly.rb
- spec/rspec/matchers/built_in/contain_exactly_spec.rb
This addresses issue #1287.
Previously, matchers retained state after being used as an argument to `RSpec::Expectations::ExpectationTarget#to`.  In particular, it leaked `@extra_items`, `@missing_items`, `@best_solution`, and `@pairings_maximizer`. This caused incorrect results when reusing a matcher in subsequent expectations.
This PR addresses the issue by reinitializing the matcher's state when the matcher is reused.
Co-authored by: Rai Feren <rferen@squareup.com>
> Allow matchers to be reused

- features/custom_matchers/define_matcher.feature
- lib/rspec/matchers/dsl.rb
I defined a custom matcher that defined some `expect(...).to ...` expectations inside the `#match` block. I got one of these expectations to fail, and then was stumped as to why the file and line number of this failure didn't appear in the backtrace. Then I stumbled across the `notify_expectation_failures` option for `#match`, and realized that I needed to set it to `true` to get the failure to appear in the backtrace.
I think this would be good to mention in the relishapp documentation? It's currently mentioned in [the API documentation](https://rspec.info/documentation/3.9/rspec-expectations/RSpec/Matchers/DSL/Macros.html), which is good, but I feel this documentation a little more obscure.
> Mention notify_expectation_failures in custom matcher docs

- lib/rspec/matchers/built_in/exist.rb
- spec/rspec/matchers/built_in/exist_spec.rb
I found that `expect(FileTest).to exist(x)` also outputs deprecation warnings in the same way as `expect(File).to exist(x)` before https://github.com/rspec/rspec-expectations/pull/954.
```
FileTest.exists? is a deprecated name, use FileTest.exist? instead
```
I confirmed that this warning is displayed on Ruby 2.7.6 and Ruby 3.1.2.
So it would be nice that we also support `FileTest` as well as `File`. It won't be used that much, but it's not a big change and it would be better to support it.
> Prevent deprecation warning from `expect(FileTest).to exist(x)`

- Gemfile
Relax rake pin to allow 12.3.3 for older ruby.
> Fix rake pin

- Changelog.md
- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
> Raise an exception when a `nil` is passed as the first argument to `raise_error`

- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
When a class that looks like a hash but has custom behaviour (such as Racks header hash which case insensitively compares keys and always assumes its asked for keys with a downcase method) we currently still try to shortcut key lookup using `key?` which than fails for fuzzy matching using matchers, instead ignore that error and use the fallback method.
> Fix `include` matcher fuzzy matched key errors when encountering hash errors

- lib/rspec/matchers/built_in/base_matcher.rb
- lib/rspec/matchers/built_in/eq.rb
- lib/rspec/matchers/built_in/eql.rb
- spec/rspec/matchers/built_in/eq_spec.rb
- spec/rspec/matchers/built_in/eql_spec.rb
closes https://github.com/rspec/rspec-expectations/issues/1422
Updates the `eq` and `eql` matchers to show detected string encoding differences - https://github.com/rspec/rspec-expectations/issues/1422
Unclear why the test is failing. For an average user this might be confusing:
```
Example F
1) Example Example
Failure/Error: expect(actual).to eq(expected)
expected: "abc"
got: "abc"
(compared using ==)
```
Immediately clear that the string encodings are not the same and the tests might be impacted by this difference:
```
Example F
1) Example Example
Failure/Error: expect(actual).to eq(expected)
expected: #<Encoding:ASCII-8BIT> "abc"
got: #<Encoding:UTF-16LE> "abc"
(compared using ==)
```
> Update matchers to show detected string encoding differences

- spec/rspec/expectations/minitest_integration_spec.rb
`rspec-core` builds are failing due to a mis-detected namespace suddenly, this namespaces it to the root to either fix or see whats going on
*edit* Turns out we were accidentally using `MiniTest` rather than `Minitest` in our tests so fix that
> Change MiniTest to Minitest

- .github/workflows/ci.yml
Experiment, only legacy should remain on 3 due to node issues.
> Update checkout 3 to 4

- lib/rspec/matchers/matcher_delegator.rb
This allows to minimize the amount of method inherited by the delegator object, and protects RSpec from new methods being introduced by future Ruby versions or monkey patched in by user code or libraries.
On modern Rubies there is `BasicObject` for this purpose, that's what `delegate.rb` uses for instance, and is considered best practice for delegators and other proxy objects. However since RSpec still support Ruby 1.8 so it's not an option.
Additionally `BasicObject` doesn't inherit from `Object` so all constant resolutions in a `BasicObject` descendant must be fully qualified which is tedious, but more importantly changing this now would probably break third party code that inherit from `MatcherDelegator`.
> Implement MatcherDelegator using the BlankSlate pattern

- Changelog.md
- lib/rspec/expectations/fail_with.rb
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/compound.rb
- lib/rspec/matchers/multi_matcher_diff.rb
- spec/rspec/matchers/built_in/compound_spec.rb
- spec/rspec/matchers/built_in/output_spec.rb
- spec/rspec/matchers/multi_matcher_diff_spec.rb
fixes https://github.com/rspec/rspec-expectations/issues/1317
fixes https://github.com/rspec/rspec-expectations/issues/1406
resolves #1319
I cherry-picked the commits from #1319 onto 3-12-maintenance, they applied without conflicts, then I ran the scripts called in the test CI action and they all passed. I pushed this to https://github.com/rspec/rspec-expectations/compare/3-12-maintenance...henrahmagix:fix-compound-redefined-actual-diff-on-3-12 just for good measure =)
I did the same on main, bundle installed fine, but I wasn't able to run any of the tests locally because I kept getting the following error:
```
$ script/run_build
============= Starting binstub check ===============
Checking required binstubs
============= Ending binstub check ===============
============= Starting specs …
```
> Fix diff for compound when transforming actual [onto main]

- features/README.md
- features/built_in_matchers/README.md
- features/built_in_matchers/all.feature
- features/built_in_matchers/be.feature
- features/built_in_matchers/be_within.feature
- features/built_in_matchers/comparisons.feature
- features/built_in_matchers/contain_exactly.feature
- features/built_in_matchers/cover.feature
- features/built_in_matchers/end_with.feature
- features/built_in_matchers/equality.feature
- features/built_in_matchers/exist.feature
- features/built_in_matchers/have_attributes.feature
- features/built_in_matchers/include.feature
- features/built_in_matchers/match.feature
- features/built_in_matchers/predicates.feature
- features/built_in_matchers/raise_error.feature
- features/built_in_matchers/respond_to.feature
- features/built_in_matchers/satisfy.feature
- features/built_in_matchers/start_with.feature
- features/built_in_matchers/throw_symbol.feature
- features/built_in_matchers/types.feature
- features/custom_matchers/define_matcher.feature
Submitted per #1446 
This pull request updates the feature and Markdown files to have the Ruby code blocks be recognized as such. In the feature files, the code block was indented one too far and so it appears to have been taken as part of quoted text. On the README files, the code blocks weren't delineated at all.
Running rake tests after this change showed no differences in Cucumbers output, but the Middleman display now shows proper code blocks.
> Updated Ruby code block markdown syntax

- lib/rspec/matchers/built_in/base_matcher.rb
Drop the `assert_ivars` and `present_ivars` methods from RSpec::Matchers::BuiltIn::BaseMatcher`.
They aren't referenced anymore, and apparently haven't been for ~10 years. I confirmed with git pickaxes, but then I also checked out a few random points in time over that period and looked for either string in the repository - no references in 2015, or at any point I looked since then.
It _is_ possible that (against your strong recommendations), people are subclassing this class for their custom matchers, but I think that's their problem. And this isn't a particularly obvious or natural method for them to be using anyway.
> Drop dead (private) methods from BaseMatcher

- Changelog.md
- lib/rspec/matchers/built_in/raise_error.rb
- spec/rspec/matchers/built_in/raise_error_spec.rb
Found this while adding coverage - there was a test that _ought_ to have covered the line in question, but didn't because it was actually slightly too loose. Tightening it up shows that it's getting the wrong error message, because the RaiseError matcher is handling `expected_error_or_message` by checking the type, and it's looking for _String_, but not Regexp there.
Figured it'd make more sense as its own PR, since it's not just test coverage. (The line _is_ covered afterwards though!)
Failure with just the test change:
```
1) expect { ... }.not_to raise_error(/message/) issues a warning
Failure/Error: expect { raise 'blarg' }.not_to raise_error(/blah/)
Kernel received :warn with unexpected arguments
expected: (match /not_to raise_error\(message\)` risks false positives/ and match …
```
> Give correct error message for `expect {}.not_to raise_error(/foo/)`

- lib/rspec/matchers/built_in/output.rb
- spec/rspec/matchers/built_in/output_spec.rb
I have an app which prints some output only if the standard output is a TTY. I'd say it's a relative standard practice:
```ruby
puts "Whatever" if $stdout.tty?
```
Currently, this can't be tested with `expect { ... }.to output(...).to_stdout` because `$stdout` is replaced with a `StringIO`, which always returns `false` for `.tty?`, so the code never prints.
If this is a problem RSpec wants to fix (I guess you can argue that it's an antipattern and should be implemented in a different way), this PR does it.
~`$stdout` is still replaced with a `StringIO` and the matcher works the same, but some specific methods are called on the original stream. I only added `.tty?` because that's my usecase, but I guess there are other methods for which this could make sense (now or in the future).~
~I …
> output matcher: add `as_tty` method to make the simulated stream behave as a TTY

- lib/rspec/matchers/built_in/has.rb
- spec/rspec/matchers/built_in/be_spec.rb
- spec/rspec/matchers/built_in/has_spec.rb
This hopefully resolves #1132 and #1288 - essentially, if you leave `strict_predicate_matchers` disabled and use a null-object spy like this:
```
let(:thing) { spy('my thing') }
it "does the thing right" do
do_it
expect(thing).to have_receivedd(:foo)
end
```
It'll pass. Note the typo in `have_receivedd`? The dynamic matcher will call `has_receivedd?` on the spy, the spy will return itself (that's what it does), and the matcher will note that the result is truthy, and pass the spec. That's kind of an issue - turning off that setting _does_ solve it, but that won't be the default until rspec 4, and even then it's not the _ideal_ behavior, just a lot better.
This PR updates the dynamic matchers to notice when their target is a Double, and change behavior slightly - for Doubles, don't just …
> Handle dynamic mocks specially for null-object doubles

- spec/rspec/expectations/block_snippet_extractor_spec.rb
- spec/rspec/expectations/failure_aggregator_spec.rb
- spec/rspec/matchers/built_in/eq_spec.rb
- spec/rspec/matchers/built_in/eql_spec.rb
- spec/rspec/matchers/built_in/yield_spec.rb
Continuing a theme from other PRs... fix some of the issues with the build on Ruby 3.4:
- Add block parameters to remove warnings
- Prevent string mutation with `<<` in favour of `+=`
- Fix output assertion for Ruby 3.4
- Prevent force_encoding warning with string literals by using `dup`
> Fix issues on Ruby 3.4.0-preview1

- Changelog.md
- lib/rspec/expectations/handler.rb
- spec/rspec/expectations/handler_spec.rb
- spec/spec_helper.rb
> Use in built rspec warnings rather than kernel

- lib/rspec/expectations/block_snippet_extractor.rb
- lib/rspec/expectations/configuration.rb
- lib/rspec/expectations/failure_aggregator.rb
- lib/rspec/matchers.rb
- lib/rspec/matchers/built_in/base_matcher.rb
- lib/rspec/matchers/built_in/change.rb
- lib/rspec/matchers/built_in/contain_exactly.rb
- lib/rspec/matchers/built_in/count_expectation.rb
- lib/rspec/matchers/built_in/has.rb
- lib/rspec/matchers/built_in/include.rb
- lib/rspec/matchers/built_in/match.rb
- lib/rspec/matchers/built_in/satisfy.rb
- lib/rspec/matchers/english_phrasing.rb
- spec/rspec/expectations/configuration_spec.rb
- spec/rspec/expectations/failure_aggregator_spec.rb
- spec/rspec/matchers/built_in/all_spec.rb
- spec/rspec/matchers/built_in/be_spec.rb
- spec/rspec/matchers/built_in/compound_spec.rb
- spec/rspec/matchers/built_in/include_spec.rb
- spec/rspec/matchers/built_in/operators_spec.rb
- spec/rspec/matchers/built_in/respond_to_spec.rb
- spec/rspec/matchers/composable_spec.rb
- spec/spec_helper.rb
Well, aside from a few lines in two other PRs (https://github.com/rspec/rspec-expectations/pull/1457 and https://github.com/rspec/rspec-expectations/pull/1456) that needed non-spec changes.
First, I found and marked all of the segments that seem to be ruby-version specific, and set them off with `:nocov:` tags. That's in the first commit. Then I started tackling the remaining uncovered lines one at a time, adding tests  I believe there to be no non-spec, non-comment changes in this PR, but I'm confident that some of the specs can be done more elegantly. Please, enhance my approaches, rspec wizards :-D
> 100% test coverage

- Changelog.md
- lib/rspec/matchers/built_in/compound.rb
- spec/rspec/matchers/built_in/compound_spec.rb
```diff
expect { arr << :foo }
-   .to change { arr }.to be_one
+   .to change { arr }.to(be_one)
.and change { arr }.to include(:foo)
```
This is to detect mismatches like this.
> Prevent mismatched composed use of value and block matchers

- Changelog.md
- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
Resolves #1478 
There are some edge-case ways you can try to invoke this matcher that end up parsing as an argument-less call and a separate expression; this will stop that from happening.
Treat instantiation of the `Include` matcher with no arguments as an ArgumentError.
This might count as a breaking change - while it _seems_ like something nobody would ever want to do, the case where this can happen legitimately comes up when the caller is taking an array to splat _into_ the `include` matcher, and ignoring the empty case because it currently passes.
> Require an argument for the Include matcher

- features/built_in_matchers/include.feature
- lib/rspec/matchers/built_in/include.rb
- spec/rspec/matchers/built_in/include_spec.rb
Fixes #1481 there was a bug where a regexp and a count contraint would work with the `include` matcher, but not a bare regexp e.g.
```
expect("astring").to include(/a/).once
expect("astring").to include(/a/)
```
This makes this consistent with the docs as working, in another version of RSpec we may look to deprecate this usage as it is not doing an `include?` call but using scan instead.
> Fix `include(/regexp/)` when used without a count.
