lib/rspec/expectations/fail_with.rb, lib/rspec/matchers/expecteds_for_multiple_diffs.rb, spec/rspec/matchers/expecteds_for_multiple_diffs_spec.rb
followup for #713 
related to rspec/rspec-support#160
=> followup for #713 :: Use differ directly instead of differ factory method

lib/rspec/matchers.rb
- hash support for include matcher
=> FIX#717 Added YARD doc

lib/rspec/matchers/fail_matchers.rb, spec/rspec/matchers_spec.rb, spec/support/matchers.rb
=> expose fail matchers for testing custom matchers

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh
=> Updates from rspec-dev (2015-02-08)

spec/rspec/expectations/configuration_spec.rb, spec/rspec/matchers/built_in/be_spec.rb, spec/rspec/matchers/built_in/contain_exactly_spec.rb, spec/rspec/matchers/built_in/eq_spec.rb, spec/rspec/matchers/built_in/exist_spec.rb, spec/rspec/matchers/built_in/include_spec.rb, spec/spec_helper.rb
Ping @myronmarston I went through and isolated out specs from the standard library.
=> Isolate specs from std lib when possible

Changelog.md, Should.md, lib/rspec/matchers/built_in/output.rb, spec/rspec/expectations_spec.rb
Built on top of rspec/rspec-support#179.
=> Allowed stdlibs

Changelog.md, lib/rspec/matchers/built_in/contain_exactly.rb, lib/rspec/matchers/built_in/raise_error.rb, lib/rspec/matchers/composable.rb, spec/rspec/matchers/built_in/raise_error_spec.rb, spec/rspec/matchers/composable_spec.rb
Supersedes #756 (and #755).  I forced the commit SHA to be different so that hopefully travis will build it.
=> Fix descriptions with ranges kick travis

lib/rspec/expectations/configuration.rb, lib/rspec/matchers/built_in/raise_error.rb, spec/rspec/expectations/configuration_spec.rb, spec/rspec/matchers/built_in/raise_error_spec.rb, spec/spec_helper.rb
=> Rename config for false positives to `warn_about_potential_false_positives`

features/built_in_matchers/be_within.feature, features/built_in_matchers/cover.feature, features/built_in_matchers/exist.feature, features/built_in_matchers/have_attributes.feature, features/built_in_matchers/include.feature, features/built_in_matchers/match.feature, features/built_in_matchers/output.feature, features/built_in_matchers/respond_to.feature, features/built_in_matchers/satisfy.feature, features/built_in_matchers/throw_symbol.feature, features/composing_matchers.feature, features/syntax_configuration.feature
These are various cosmetic enhancements to the Markdown source files of the Cucumber features. The commit messages are hopefully self-explanatory. Let me know if squashing is required, or if the commit messages are not clear enough.
=> [Documentation] [Features] Various cosmetic enhancements

lib/rspec/expectations/failure_aggregator.rb, spec/rspec/expectations/failure_aggregator_spec.rb
This should fix the JRuby failures happening on rspec/rspec-core#1977.
=> Deal with JRuby caller vs raise stacktrace differences.

lib/rspec/expectations/failure_aggregator.rb, lib/rspec/matchers/dsl.rb, spec/rspec/expectations/failure_aggregator_spec.rb
This is the necessary changes to support rspec/rspec-mocks#956.
=> Dedup exceptions

features/built_in_matchers/all.feature, features/built_in_matchers/include.feature, features/custom_matchers/define_diffable_matcher.feature, features/custom_matchers/define_matcher.feature
Hi this is a follow up to #807,
this adds some more documentation than requested, but I hope you find that useful. 
I tried to document all the input you - @myronmarston - gave me on different issues here on github. I found that very helpful and thought that might be helpful for others as well.
=> Add some documentation for custom matchers

Changelog.md, lib/rspec/matchers.rb, spec/rspec/matchers/aliased_matcher_spec.rb, spec/rspec/matchers_spec.rb, spec/spec_helper.rb
=> Warn about MRI 1.9 `super` infinite recursion bug.

features/custom_matchers/define_matcher.feature
@myronmarston @JonRowe To make it easier for others to find the matcher protocol.
=> Add link to documentation

README.md
=> Fixing typo for build detail link

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh
=> Updates from rspec-dev (2015-08-13)

Changelog.md, lib/rspec/matchers/built_in/match.rb, spec/rspec/matchers/built_in/captures_spec.rb
See #831 for details/discussion.
=> Add a match(...).with_captures(...) matcher.

lib/rspec/matchers/built_in/match.rb, spec/rspec/matchers/built_in/captures_spec.rb
needed newlines
removed unused method
consistent use of a_hash_including matcher
=> MatchWithCaptures cleanup

features/custom_matchers/define_matcher.feature
Previously there was no way to discover this.
@rspec/rspec please merge if green and you have no feedback!
=> Add relish documentation for block_arg.

rspec-expectations.gemspec
=> Link to homepage using https

lib/rspec/matchers/built_in/change.rb, spec/rspec/matchers/built_in/change_spec.rb
C.f. issue https://github.com/rspec/rspec-expectations/issues/907.
=> Clarify what happened in error message.

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh
=> Updates from rspec-dev (2016-05-04)

.rubocop_rspec_base.yml, .travis.yml, Gemfile, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh
=> Updates from rspec-dev (2016-07-14)

lib/rspec/expectations/fail_with.rb, lib/rspec/matchers/english_phrasing.rb
An alternative to #936, this takes the low hanging fruit but leaves the more controversial diff change in behaviour behind.
=> Alternate reduce allocations

Gemfile
=> switch git from git to https

lib/rspec/matchers/built_in/exist.rb, spec/rspec/matchers/built_in/exist_spec.rb
=> Prevent warning when exists matcher is used with files

Changelog.md, lib/rspec/matchers/built_in/be.rb, spec/rspec/matchers/built_in/be_spec.rb
=> Treat no method errors as not comparable

lib/rspec/matchers/built_in/base_matcher.rb, lib/rspec/matchers/built_in/be.rb, lib/rspec/matchers/built_in/respond_to.rb, lib/rspec/matchers/built_in/yield.rb, spec/rspec/matchers/built_in/change_spec.rb, spec/rspec/matchers/built_in/equal_spec.rb, spec/rspec/matchers/built_in/operators_spec.rb, spec/rspec/matchers/built_in/yield_spec.rb, spec/rspec/matchers/dsl_spec.rb
All the details are discussed in https://github.com/rspec/rspec-core/pull/2437
=> Updates for frozen-string-literal compatibility.

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh
=> Updates from rspec-dev (2017-11-13)

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh
=> Updates from rspec-dev (2018-01-02)

README.md
Replacement of #1060 since it was closed, builds on @ianfixes work with some language tweaks.
=> Improve documentation surrounding array matchers

lib/rspec/matchers/built_in/be_instance_of.rb, lib/rspec/matchers/built_in/be_kind_of.rb, spec/rspec/matchers/built_in/be_instance_of_spec.rb, spec/rspec/matchers/built_in/be_kind_of_spec.rb
Hi,
I added warning message for #1105 as a special failure message.
=> Added warning message for #1105

lib/rspec/matchers/built_in/be_instance_of.rb, lib/rspec/matchers/built_in/be_kind_of.rb, spec/rspec/matchers/built_in/be_instance_of_spec.rb, spec/rspec/matchers/built_in/be_kind_of_spec.rb
=> "KindOf" matchers: Rescue `NoMethodError` instead of `respond_to?` check

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2019-07-24)

.rubocop_rspec_base.yml, .travis.yml, appveyor.yml, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/travis_functions.sh, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2019-12-26)

Changelog.md, lib/rspec/expectations/handler.rb, spec/rspec/expectations/handler_spec.rb
- See: https://github.com/rspec/rspec-mocks/issues/1250
=> Be able to set custom failure message with mocks

lib/rspec/matchers/built_in/respond_to.rb
Extracting arity logic to reduce class length.
Removes a class length exclusion, alternative to #1178
=> Refactor respond to matcher 

lib/rspec/matchers/built_in/be_within.rb, spec/rspec/matchers/built_in/be_within_spec.rb
Spotted by @kwstannard in #1182
=> Format expected within the be_within description

spec/rspec/matchers/built_in/be_spec.rb
I merged #1208 on a green status but it seemed the build had not passed, but not updated Github, this fixes the build.
=> Replace symbol array constructor

benchmarks/count_vs_select_size.rb
=> Add benchmark for count vs select size

.github/workflows/ci.yml, .rubocop_rspec_base.yml, .travis.yml, features/custom_matchers/define_diffable_matcher.feature, features/support/diff_lcs_versions.rb, lib/rspec/expectations/failure_aggregator.rb, script/ci_functions.sh, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/update_rubygems_and_install_bundler, spec/rspec/expectations/failure_aggregator_spec.rb, spec/spec_helper.rb
=> Updates from rspec-dev (2020-11-22)

.github/workflows/ci.yml, .rubocop_rspec_base.yml, .travis.yml, script/ci_functions.sh, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2020-12-21)

features/support/disallow_certain_apis.rb, features/syntax_configuration.feature, spec/spec_helper.rb
https://github.com/rspec/rspec-core/pull/2819#issuecomment-751375468
=> Make specs inter-dependent, and backwards compatible'ish

.github/workflows/ci.yml, .rubocop_rspec_base.yml, features/support/disallow_certain_apis.rb, script/ci_functions.sh, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2020-12-27)

.github/workflows/ci.yml, .rubocop_rspec_base.yml, .travis.yml, script/ci_functions.sh, script/clone_all_rspec_repos, script/functions.sh, script/legacy_setup.sh, script/predicate_functions.sh, script/run_build, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2021-01-02)

.github/workflows/ci.yml, .rubocop_rspec_base.yml, .travis.yml, script/ci_functions.sh, script/clone_all_rspec_repos, script/cucumber.sh, script/functions.sh, script/legacy_setup.sh, script/predicate_functions.sh, script/run_build, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2021-01-08)

spec/spec_helper.rb
See https://github.com/rspec/rspec-core/pull/2864
=> Do not use the removed color config option

spec/rspec/expectations/block_snippet_extractor_spec.rb, spec/rspec/matchers/built_in/change_spec.rb, spec/rspec/matchers/built_in/satisfy_spec.rb
Related to https://github.com/rspec/rspec-core/issues/1821
=> Use :skip instead of :if/:unless

.github/workflows/ci.yml, .rubocop_rspec_base.yml, Gemfile, features/built_in_matchers/change.feature, script/ci_functions.sh, script/clone_all_rspec_repos, script/functions.sh, script/predicate_functions.sh, script/run_build, script/run_rubocop, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2022-09-09)

lib/rspec/matchers/dsl.rb, spec/rspec/matchers/aliased_matcher_spec.rb
=> Support keyword argument delegation on aliased and negated matchers

.github/dependabot.yml, .github/workflows/ci.yml, .rubocop_rspec_base.yml, script/ci_functions.sh, script/clone_all_rspec_repos, script/cucumber.sh, script/functions.sh, script/legacy_setup.sh, script/predicate_functions.sh, script/run_build, script/run_rubocop, script/update_rubygems_and_install_bundler, spec/rspec/matchers/dsl_spec.rb
=> Updates from rspec-dev (2023-03-09)

.github/dependabot.yml, .github/workflows/ci.yml, .rubocop_rspec_base.yml, script/ci_functions.sh, script/clone_all_rspec_repos, script/cucumber.sh, script/functions.sh, script/legacy_setup.sh, script/predicate_functions.sh, script/run_build, script/run_rubocop, script/update_rubygems_and_install_bundler, spec/rspec/matchers/dsl_spec.rb
=> Updates from rspec-dev (2023-03-12)

.github/dependabot.yml, .github/workflows/ci.yml, .rubocop_rspec_base.yml, Gemfile, script/ci_functions.sh, script/clone_all_rspec_repos, script/cucumber.sh, script/functions.sh, script/legacy_setup.sh, script/predicate_functions.sh, script/run_build, script/run_rubocop, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2024-02-23)

DEV-README.md, README.md, features/README.md, features/built_in_matchers/README.md, features/built_in_matchers/all.feature, features/built_in_matchers/be.feature, features/built_in_matchers/be_within.feature, features/built_in_matchers/comparisons.feature, features/built_in_matchers/contain_exactly.feature, features/built_in_matchers/cover.feature, features/built_in_matchers/end_with.feature, features/built_in_matchers/equality.feature, features/built_in_matchers/exist.feature, features/built_in_matchers/have_attributes.feature, features/built_in_matchers/include.feature, features/built_in_matchers/match.feature, features/built_in_matchers/predicates.feature, features/built_in_matchers/raise_error.feature, features/built_in_matchers/respond_to.feature, features/built_in_matchers/satisfy.feature, features/built_in_matchers/start_with.feature, features/built_in_matchers/throw_symbol.feature, features/built_in_matchers/types.feature, features/built_in_matchers/yield.feature, features/custom_matchers/define_matcher.feature, features/custom_matchers/define_matcher_outside_rspec.feature, features/customized_message.feature
Builds off #1447 but tweaks the indentation
=> Fix documentation indentation

features/built_in_matchers/raise_error.feature
I had to do some digging on google to find that, having on the official docs might help some people :)
=> add example on how to use raise_error with block

.github/dependabot.yml, .github/workflows/ci.yml, .rubocop_rspec_base.yml, features/step_definitions/additional_cli_steps.rb, script/ci_functions.sh, script/clone_all_rspec_repos, script/cucumber.sh, script/functions.sh, script/legacy_setup.sh, script/predicate_functions.sh, script/run_build, script/run_rubocop, script/update_rubygems_and_install_bundler
=> Updates from rspec-dev (2024-07-15)
